clusters = source, target

source.bootstrap.servers = source-kafka:29092
target.bootstrap.servers = cloud-kafka:39092

source->target.enabled = true
target->source.enabled = false

source->target.topics = ((client|operational)[.].*|pg1[.]transaction)
source->target.groups = .*

refresh.topics.interval.seconds = 5
refresh.groups.interval.seconds = 5

replication.factor = 1
checkpoints.topic.replication.factor = 1
heartbeats.topic.replication.factor = 1
offset-syncs.topic.replication.factor = 1

offset-syncs.topic.partitions = 1
checkpoints.topic.partitions = 1
heartbeats.topic.partitions = 1

offset.storage.topic = local-mm2-offsets.target.internal
config.storage.topic = local-mm2-configs.target.internal
status.storage.topic = local-mm2-status.target.internal

offset.storage.partitions = 1
config.storage.partitions = 1
status.storage.partitions = 1

offset.storage.replication.factor = 1
config.storage.replication.factor = 1
status.storage.replication.factor = 1

admin.request.timeout.ms = 60000
request.timeout.ms = 60000

replication.policy.class = org.apache.kafka.connect.mirror.IdentityReplicationPolicy
