SELECT 'CREATE ROLE dbz WITH LOGIN PASSWORD ''dbz'' REPLICATION'
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'dbz')
\gexec

GRANT CONNECT, CREATE ON DATABASE appdb TO dbz;

CREATE SCHEMA IF NOT EXISTS inventory AUTHORIZATION dbz;
